---
resources:

- name: source-code
  type: git
  source:
    uri: https://github.com/evsinev/socket-nio.git

jobs:

- name: test

  plan:

  - get: source-code
    trigger: true

  - task: test-8
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.5-jdk-8-alpine
      inputs:
      - name: source-code
      run:
        path: "mvn"
        args: ["-f", "source-code/pom.xml", "test"]
